---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: rchain-coop
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: kayvan.kazeminejad@rchain.coop
    privateKeySecretRef:
      name: letsencrypt-staging-tls
    http01: {}
