apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: dev
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kayvan@q2ip.com
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
