apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "kayvan@q2io.com"
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
