---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: "nginx-secret"
spec:
  secretName: "nginx-secret"
  dnsNames:
  - "dev-rchain.tk"
  acme:
    config:
    - http01:
        ingressClass: "nginx"
      domains:
      - "dev-rchain.tk"
  issuerRef:
    name: "letsencrypt-staging"
    kind: ClusterIssuer
