---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "rchain-coop"
  annotations:
    kubernetes.io/ingress.global-static-ip-name: www-rchain-coop
  labels:
    app: rchain-coop
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: "rchain-coop"
          servicePort: 3000
