---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rchain-coop
  namespace: rchain-coop
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/issuer: letsencrypt-staging
spec:
  rules:
  - host: rchain-coop.tk
    http:
      paths:
        - backend:
            serviceName: rchain-coop
            servicePort: 3000
          path: /* 
  tls:
    - secretName: letsencrypt-staging-tls
      hosts:
        - rchain-coop.tk
