---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "rchain-coop"
  annotations:
    kubernetes.io/ingress.global-static-ip-name: www-rchain-coop

  labels:
    app: rchain-coop
spec:
  tls:
    - secretName: letsencrypt-staging-dev
      hosts:
      - rchain-coop.tk
  rules:
  - host: rchain-coop.tk
    http:
      paths:
        - backend:
            serviceName: "rchain-coop"
            servicePort: 3000
