---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rchain-coop
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
  labels:
    app: rchain-coop
spec:
  tls:
    - secretName: letsencrypt-staging-tls
      hosts:
      - rchain-coop.tk
  rules:
  - host: rchain-coop.tk
    http:
      paths: 
        - path: 
          backend:
            serviceName: rchain-coop
            servicePort: 3000
