---
apiVersion: v1
kind: Service
metadata:
  name: rchain-coop
  labels:
    app: rchain-coop
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      protocol: TCP
  selector:
    app: rchain-coop
