---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}"
  labels:
    app: "{{ .Values.app.name }}"
spec:
  type: ClusterIP 
  ports:
    - name: http
      port: {{ .Values.app.port }}
      protocol: TCP
  selector:
    app: "{{ .Values.app.name }}"
